### ISSUE TITLE
@leafer-in/arrow创建Arrow报错

### ISSUE THREAD

**Issue by FliPPeDround** [leaferjs/in#1]
![image](https://github.com/user-attachments/assets/0f238050-afb3-4863-818a-c02a7f05b7b1)

复现[Playground](https://cloudstudio.net/a/21616030077784064?channel=share&sharetype=URL)

**Comment by leaferjs** [comment]
收到，谢谢反馈，是版本更新的原因，可以先用github本地环境体验，或create-leafer命令行工具～

**Comment by leaferjs** [comment]
可以去用了
